server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/appointment?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: APPOINTMENT-SERVICE
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
notification-service:
  base-url: http://NOTIFICATION-MANAGEMENT-SERVICE
user-management-service:
  base-url: http://USER-MANAGEMENT